name: "miniDLNA for Home Assistant (HA)"
version: 0.1.1g-tst19
description: "This app (~addon) provides you with the latest miniDLNA on Alpine..."
slug: minidlna

url: https://github.com/Moozzuzz/Apps4HA/tree/main/miniDLNA
arch:
  - aarch64
  - amd64

ports:
  1900/udp: 1900

map:
  - config:rw
  - ssl:rw
  - addons:rw
  - share:rw
  - backup:rw
  - media:rw

#homeassistant_api: true
hassio_api: true
# niet beide tegelijk
hassio_role: homeassistant

privileged:
  - NET_ADMIN
  - SYS_ADMIN
  - DAC_READ_SEARCH

devices:
  - /dev/net/tun

host_network: true

startup: services
init: false
boot: auto
backup: cold

# ingress: false # true
# ingress_port: 9998
# webui: http://[HOST]:[PORT:9998]

panel_icon: mdi:dlna
panel_title: miniDLNA

options:
  media_dir: /media;/share
  options: -d
  friendly_name: HA miniDLNA

schema:
  media_dir: str
  options: str
  friendly_name: str
